name: Get and commit updated pathway data
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # if [ $statusCode -eq "200" ]; then echo "success"; else echo "failure"; fi
    - cron:  '12 * * * *'
  push:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get updated pathway data
        id: get_pathway_data
        run: |
          statusCode=$(curl $REACT_APP_MERAKI_URL/pathways?courseType=json -H "version-code: 40" -o data/pathway_datav40.json -w "%{http_code}")
          echo "::set-output name=status_code::$statusCode"
          if [ $statusCode -eq "200" ]; then echo "success"; else exit 0; fi
        env:
          REACT_APP_MERAKI_URL: https://api.merakilearn.org
      - name: Commit pathway data
        run: |
          if [[ ${{ steps.get_pathway_data.outputs.status_code }} != 200 ]]; then exit 0; fi
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/pathway_datav40.json
          # https://stackoverflow.com/a/25149786 for git status --porcelain
          if [[ `git status --porcelain` ]]; then
            git commit -m "Update pathway data on $(date)"
            git push
          else
            echo "No new changes"
          fi
