name: Get and commit updated pathway data
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # if [ $statusCode -eq "200" ]; then echo "success"; else echo "failure"; fi
    - cron:  '12 * * * *'
  push:
jobs:
  save_updated_data:
    runs-on: ubuntu-latest
    env:
      FRONT_END_DATA_FILE_PATH: data/front-end_pathway_data.json
      BACK_END_DATA_FILE_PATH: data/be_pathway_datav40-1.json
      JOINED_DATA_FILE_PATH: data/pathway_datav40.json
      JOIN_SCRIPT_PATH: join_front_and_back-end_data.js 
    steps:
      - uses: actions/checkout@v3
      - name: Get and store updated back-end pathway data
        id: get_pathway_data
        run: |
          statusCode=$(curl $REACT_APP_MERAKI_URL/pathways?courseType=json -H "version-code: 40" -o $BACK_END_DATA_FILE_PATH -w "%{http_code}")
          echo "::set-output name=status_code::$statusCode"
          if [ $statusCode -eq "200" ]; then
            echo "::set-output name=status_code::$statusCode"

            echo "Successfully retrieved front- and back-end pathway data"
          else
            echo "Failed to get back-end data with error $statusCode"
            exit 0 
          fi
        env:
          REACT_APP_MERAKI_URL: https://api.merakilearn.org
      - name: Join back- and front-end pathway data
        id: join_pathway_data
        run: |
          echo "TODO merging..."
          npm install @actions/core
          npm install fs
          node $JOIN_SCRIPT_PATH $FRONT_END_DATA_FILE_PATH $BACK_END_DATA_FILE_PATH
      - name: Commit pathway data
        run: |
          echo "${{ steps.join_pathway_data.outputs.joined_pathway_data }}"
          if [[ ${{ steps.get_pathway_data.outputs.status_code }} != 200 ]]; then exit 0; fi
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add $BACK_END_DATA_FILE_PATH
          # https://stackoverflow.com/a/25149786 for git status --porcelain
          if [[ `git status --porcelain` ]]; then
            git commit -m "Update pathway data on $(date)"
            git push
            echo "Successfully saved pathway data"
          else
            echo "No new changes"
          fi
