name: Get and commit updated pathway data
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 * * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get updated pathway data
        run: |
          curl https://api.merakilearn.org/pathways?courseType=json > pathway_data.json
        env:
          MERAKI_URL: https://api.merakilearn.org/pathways
      - name: Commit pathway data
        run: |
          git config --global user.name 'Pathways Bot'
          git config --global user.email 'jschanker@users.noreply.github.com'
          git add pathway_data.json
          git commit -am "Update pathway data"
          git push
