name: Get and commit updated pathway data
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # if [ $statusCode -eq "200" ]; then echo "success"; else echo "failure"; fi
    - cron:  '12 * * * *'
  push:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get updated pathway data
        id: get_pathway_data
        run: |
          statusCode=$(curl https://api.merakilearn.org/pathways?courseType=json -o pathway_data2.json -w "%{http_code}")
          if [ $statusCode -eq "200" ]; then echo "success"; else exit 0; fi
        env:
          MERAKI_URL: https://api.merakilearn.org/pathways
      - name: Commit pathway data
        run: |
          if [[ ${{ steps.get_pathway_data.outputs.status_code }} ]]; then exit 0; fi
          git add pathway_data2.json
          git commit -am "Update pathway data"
          git push
