# https://stackoverflow.com/a/58393457
name: Push commit
on:
  push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make commit with data
        run: |
          "hey" > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'jschanker@users.noreply.github.com'
          git commit -am "Testing"
          git push
