# https://stackoverflow.com/a/58393457
name: Push commit
on:
  pull_request
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make commit with data
        run: |
          ( echo -n const pathwayData = ; curl https://api.merakilearn.org/pathways?courseType=json; echo -n \; ) | cat > pathway_data.js
      - name: Commit pathway data
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'jschanker@users.noreply.github.com'
          git add pathway_data.js
          git commit -am "Testing"
          git push
